set_property PACKAGE_PIN H16 [get_ports TMDS_CLK_P]
set_property PACKAGE_PIN B19 [get_ports {TMDS_DATA_P[2]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_DATA_P[1]}]
set_property PACKAGE_PIN D19 [get_ports {TMDS_DATA_P[0]}]
set_property PACKAGE_PIN K17 [get_ports CLK]
set_property PACKAGE_PIN F17 [get_ports HDMI_OUT_EN]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_OUT_EN]

set_property PACKAGE_PIN M19 [get_ports KEY_TURNLEFT]
set_property PACKAGE_PIN M20 [get_ports KEY_TURNRIGHT]
set_property PACKAGE_PIN F16 [get_ports KEY_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports KEY_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports KEY_TURNLEFT]
set_property IOSTANDARD LVCMOS33 [get_ports KEY_TURNRIGHT]
